apiVersion: v1
kind: Pod
metadata:
	name: gateway-pod
	labels:
		app: gateway
		type: microservice
spec:
	container:
		- name: gateway-app
		  image: oresteslacunza/serviciosapigateway:latest
		  ports:
			- containerPort: 80