apiVersion: apps/v1
kind: Deployment
metadata:
	name: gateway-deploy
	labels:
		name: gateway-deploy
		app: microservice
spec:
	replicas: 2
	selector:
		matchLabels:
			app: gateway
			type: microservices
	template:
		metadata:
			name: gateway-pod
			labels:
				app: gateway
				type: microservices
		spec:
			container:
				- name: gateway-app
					image: oresteslacunza/serviciosapigateway:latest
					ports:
				- containerPort: 80