apiVersion: v1
kind: Pod
metadata:
	name: microservice-libreria-pod
	labels:
		app: microservice-libreria
		type: microservice
spec:
	container:
		- name: microservice-libreria-app
		  image: oresteslacunza/serviciosapilibreria:latest
		  ports:
			- containerPort: 80
		  env:
			- name: MongoDb__ConnectionString
			  value: mongodb://olacunza:murcielago147@mongo-service:27017