apiVersion: apps/v1
kind: Deployment
metadata:
	name: microservice-libreria-deploy
	labels:
		name: microservices-libreria-deploy
		app: microservice
spec:
	replicas: 2
	selector:
		matchLabels:
			app: microservice-libreria
			type: microservices
	template:
		metadata:
			name: microservice-libreria-pod
			labels:
				app: microservice-libreria
				type: microservices
		spec:
			container:
				- name: microservice-libreria-app
					image: oresteslacunza/serviciosapilibreria:latest
					ports:
						- containerPort: 80
					env:
						- name: MongoDb__ConnectionString
						  value: mongodb://olacunza:murcielago147@mongo-service:27017