apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:6.0.2
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "olacunza"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "Murcielago147!"
      ports:
        - containerPort: 27017